# Generated by Django 3.2 on 2021-04-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Longitude', models.FloatField(help_text='Longitude of the sight')),
                ('Latitude', models.FloatField(help_text='Latitude of the sight')),
                ('Unique_Squirrel_Id', models.CharField(help_text='The unique ID of the squirrel', max_length=25)),
                ('Shift', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Shift of the sight', max_length=16)),
                ('Date', models.DateField(blank=True, help_text='Date of the sight in yyyy-mm-dd', null=True)),
                ('Age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), (None, '')], help_text='Age of the squirrel', max_length=16)),
                ('Primary_Fur_Color', models.CharField(blank=True, help_text='Fur color', max_length=16)),
                ('Location', models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground'), (None, '')], help_text='Location', max_length=128)),
                ('Specific_Location', models.CharField(blank=True, help_text='Additional notes to the location', max_length=128)),
                ('Running', models.BooleanField(blank=True, help_text='Running', null=True)),
                ('Chasing', models.BooleanField(blank=True, help_text='Chasing', null=True)),
                ('Climbing', models.BooleanField(blank=True, help_text='Climbing', null=True)),
                ('Eating', models.BooleanField(blank=True, help_text='Eating', null=True)),
                ('Foraging', models.BooleanField(blank=True, help_text='Foraging', null=True)),
                ('Other_Activities', models.CharField(blank=True, help_text='Other Activities', max_length=128, null=True)),
                ('Kuks', models.BooleanField(blank=True, help_text='Kuks', null=True)),
                ('Quaas', models.BooleanField(blank=True, help_text='Quaas', null=True)),
                ('Moans', models.BooleanField(blank=True, help_text='Moans', null=True)),
                ('Tail_Flags', models.BooleanField(blank=True, help_text='Tail_Flags', null=True)),
                ('Tail_Twitches', models.BooleanField(blank=True, help_text='Tail_Twitches', null=True)),
                ('Approaches', models.BooleanField(blank=True, help_text='Approaches', null=True)),
                ('Indifferent', models.BooleanField(blank=True, help_text='Indifferent', null=True)),
                ('Runs_From', models.BooleanField(blank=True, help_text='Runs_From', null=True)),
            ],
        ),
    ]
